.TH KIWMI 1 "2018 November 9" "{{VERSION}}" ""

.SH NAME
kiwmi \- fully manual tiling window manager

.SH SYNPOSIS
.B kiwmi
.R [
.B -h
.R |
.B -v
.R |
.B -c
.I CONFIG_PATH
.R ]

.B seed
.I COMMAND

.SH DESCRIPTION
Starts the
.B kiwmi
window manager on
.IR DISPLAY .
It is controlled and configured via
.BR seed .

A list of
.IR COMMAND s
can be found below.

.SH OPTIONS

.B \-h
.RS
Print help and exit
.RE

.B \-v
.RS
Print version info and exit
.RE

.B \-d
.RS
Print debug information
.RE

.B \-c
.I CONFIG_PATH
.RS
Choose a different config path. Default is
.I ${XDG_CONFIG_HOME}/kiwmi/kiwmirc
.RE

.SH USAGE
Possible commands for
.B seed
are:

.B quit
.RS
Quit kiwmi
.RE

.B reload
.RS
Reload the configuration file.
.RE

.B exec
.I COMMAND
.RS
Replaces the kiwmi instance with
.IR COMMAND .
This can be used to restart kiwmi after an update, for example.
.RE

.SH AUTHOR
Niclas Meyer <niclas@countingsort.com>
